JavaScript: true
engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - resources/**/*
  - lib/**/*
exclude_paths:
- test/**/*
